export const STRINGS = {
  productName: 'VizLoop',
  splashSubtitle: 'Code becomes concept, motion, and final answer.',
  authPromise: 'Build program-flow intuition with guided traces, games, and assessment.',
  syncMessage: 'Syncing your progress...',
};

export const CONCEPT_TREE = [
  {
    id: 'arrays',
    title: 'Arrays',
    route: '#/hub/arrays',
    summary: 'Store many values under one name and access them by index.',
    keywords: ['list', 'index', '2d array', 'matrix', 'traversal'],
    progressKey: 'arrays',
    sampleId: 'filter-scores-js',
    subtopics: [
      {
        id: 'arrays-1d',
        title: '1D Arrays',
        summary: 'Read and update one row of values.',
        sampleId: 'filter-scores-js',
        related: ['loops-for', 'searching-linear'],
      },
      {
        id: 'arrays-2d',
        title: '2D Arrays',
        summary: 'Think in rows and columns for matrices and grids.',
        sampleId: 'priority-orders-py',
        related: ['loops-nested', 'graphs'],
      },
    ],
  },
  {
    id: 'loops',
    title: 'Loops',
    route: '#/hub/loops',
    summary: 'Repeat a block of code while a rule stays true.',
    keywords: ['for loop', 'while loop', 'counter', 'iteration', 'off by one'],
    progressKey: 'loops',
    sampleId: 'print-1-10-js',
    subtopics: [
      {
        id: 'loops-for',
        title: 'For Loop',
        summary: 'Use a counter when the number of repetitions is known.',
        sampleId: 'print-1-10-js',
        related: ['arrays-1d', 'sorting'],
      },
      {
        id: 'loops-while',
        title: 'While Loop',
        summary: 'Repeat while a condition stays true.',
        sampleId: 'print-1-10-py',
        related: ['recursion', 'searching-linear'],
      },
      {
        id: 'loops-nested',
        title: 'Nested Loops',
        summary: 'Use one loop inside another for tables, grids, and matrices.',
        sampleId: 'priority-orders-py',
        related: ['arrays-2d', 'sorting'],
      },
    ],
  },
  {
    id: 'stack',
    title: 'Stack',
    route: '#/hub/stack',
    summary: 'Last in, first out: push, pop, and peek.',
    keywords: ['push', 'pop', 'peek', 'lifo'],
    progressKey: 'stack',
    sampleId: 'print-1-10-js',
    subtopics: [],
  },
  {
    id: 'queue',
    title: 'Queue',
    route: '#/hub/queue',
    summary: 'First in, first out: enqueue and dequeue.',
    keywords: ['enqueue', 'dequeue', 'fifo'],
    progressKey: 'queue',
    sampleId: 'print-1-10-py',
    subtopics: [],
  },
  {
    id: 'linked-list',
    title: 'Linked List',
    route: '#/hub/linked-list',
    summary: 'Nodes connected by references instead of indexes.',
    keywords: ['node', 'next pointer', 'insert', 'delete'],
    progressKey: 'linked-list',
    sampleId: 'filter-scores-js',
    subtopics: [],
  },
  {
    id: 'trees',
    title: 'Trees',
    route: '#/hub/trees',
    summary: 'Hierarchical nodes with roots, parents, and children.',
    keywords: ['binary tree', 'root', 'leaf', 'traversal'],
    progressKey: 'trees',
    sampleId: 'priority-orders-py',
    subtopics: [],
  },
  {
    id: 'graphs',
    title: 'Graphs',
    route: '#/hub/graphs',
    summary: 'Vertices and edges for networks, paths, and relationships.',
    keywords: ['vertex', 'edge', 'bfs', 'dfs'],
    progressKey: 'graphs',
    sampleId: 'filter-scores-js',
    subtopics: [],
  },
  {
    id: 'recursion',
    title: 'Recursion',
    route: '#/hub/recursion',
    summary: 'A function solving a smaller version of the same problem.',
    keywords: ['base case', 'recursive call', 'call stack'],
    progressKey: 'recursion',
    sampleId: 'print-1-10-py',
    subtopics: [],
  },
  {
    id: 'sorting',
    title: 'Sorting',
    route: '#/hub/sorting',
    summary: 'Rearrange values into a meaningful order.',
    keywords: ['bubble sort', 'merge sort', 'swap', 'compare'],
    progressKey: 'sorting',
    sampleId: 'priority-orders-py',
    subtopics: [],
  },
  {
    id: 'searching',
    title: 'Searching',
    route: '#/hub/searching',
    summary: 'Find a value by checking candidates intelligently.',
    keywords: ['linear search', 'binary search', 'target'],
    progressKey: 'searching',
    sampleId: 'filter-scores-js',
    subtopics: [
      {
        id: 'searching-linear',
        title: 'Linear Search',
        summary: 'Check one item at a time until the target appears.',
        sampleId: 'filter-scores-js',
        related: ['arrays-1d', 'loops-for'],
      },
    ],
  },
];

export const QUESTION_BANK_VERSION = 'assessment-bank-2026.09.03';

export const QUESTION_BANK = [
  {
    id: 'loops-beginner-counter-output',
    language: 'JavaScript',
    level: 'Beginner',
    topic: 'loops',
    question: 'What does the loop print first?',
    code: 'for (let i = 1; i <= 3; i++) { console.log(i); }',
    options: ['0', '1', '3', '4'],
    correctOptionIndex: 1,
    explanation: 'The initializer sets i to 1 before the first condition check.',
  },
  {
    id: 'loops-beginner-stop',
    language: 'Python',
    level: 'Beginner',
    topic: 'loops',
    question: 'Why does range(1, 4) stop before 4?',
    code: 'for i in range(1, 4): print(i)',
    options: ['Python ranges stop before the ending value', 'The print statement blocks 4', 'The loop runs backward', 'range only accepts three numbers'],
    correctOptionIndex: 0,
    explanation: 'Python includes the start value but excludes the stop value.',
  },
  {
    id: 'arrays-beginner-index',
    language: 'JavaScript',
    level: 'Beginner',
    topic: 'arrays',
    question: 'In scores[i], what does i represent?',
    code: 'const scores = [4, 7, 2];',
    options: ['The array length', 'The current index', 'The final answer', 'A hidden copy of scores'],
    correctOptionIndex: 1,
    explanation: 'The index points to one position inside the array.',
  },
  {
    id: 'conditions-beginner-threshold',
    language: 'JavaScript',
    level: 'Beginner',
    topic: 'conditions',
    question: 'Which values pass the condition value > 5?',
    code: 'values = [4, 7, 9]',
    options: ['4 only', '7 and 9', '4 and 7', 'all values'],
    correctOptionIndex: 1,
    explanation: 'Only values strictly greater than 5 pass.',
  },
  {
    id: 'stack-intermediate-lifo',
    language: 'JavaScript',
    level: 'Intermediate',
    topic: 'stack',
    question: 'After push(2), push(5), pop(), what value is removed?',
    code: 'stack.push(2); stack.push(5); stack.pop();',
    options: ['2', '5', '0', 'both values'],
    correctOptionIndex: 1,
    explanation: 'A stack removes the most recently added item first.',
  },
  {
    id: 'sorting-intermediate-swap',
    language: 'Python',
    level: 'Intermediate',
    topic: 'sorting',
    question: 'In bubble sort, why do adjacent values swap?',
    code: 'if items[i] > items[i + 1]: swap(items[i], items[i + 1])',
    options: ['To move a larger value rightward', 'To delete duplicates', 'To reverse every loop', 'To skip comparisons'],
    correctOptionIndex: 0,
    explanation: 'Each swap pushes a larger unsorted value closer to its final position.',
  },
  {
    id: 'graphs-advanced-traversal',
    language: 'Python',
    level: 'Advanced',
    topic: 'graphs',
    question: 'What does BFS usually use to remember the next vertex to visit?',
    code: 'queue.enqueue(start)',
    options: ['Stack', 'Queue', 'Hash only', 'Binary tree'],
    correctOptionIndex: 1,
    explanation: 'Breadth-first search explores older discovered vertices first, so a queue fits.',
  },
  {
    id: 'recursion-advanced-base-case',
    language: 'JavaScript',
    level: 'Advanced',
    topic: 'recursion',
    question: 'Why does recursion need a base case?',
    code: 'function fact(n) { if (n === 1) return 1; return n * fact(n - 1); }',
    options: ['To stop infinite self-calls', 'To make arrays faster', 'To create a loop counter', 'To hide variables'],
    correctOptionIndex: 0,
    explanation: 'The base case is the stopping rule that prevents endless recursive calls.',
  },
];

export const GAME_LIBRARY = [
  {
    id: 'fill-blanks',
    title: 'Fill in the Blanks',
    summary: 'Complete one missing token and validate by expected output.',
    conceptId: 'loops',
    difficulty: 'Easy',
  },
  {
    id: 'spot-bug',
    title: 'Spot the Bug',
    summary: 'Click the buggy line and reveal a grounded fix.',
    conceptId: 'loops',
    difficulty: 'Easy',
  },
  {
    id: 'trace-loop',
    title: 'Trace the Loop',
    summary: 'Predict the next variable value before the trace reveals it.',
    conceptId: 'loops',
    difficulty: 'Easy',
  },
  {
    id: 'stack-queue',
    title: 'Stack / Queue Sorter',
    summary: 'Simulate push, pop, enqueue, and dequeue in the right order.',
    conceptId: 'stack',
    difficulty: 'Easy',
  },
  {
    id: 'sorting-race',
    title: 'Sorting Race',
    summary: 'Perform comparisons and swaps manually.',
    conceptId: 'sorting',
    difficulty: 'Moderate',
  },
  {
    id: 'big-o',
    title: 'Big-O Guess',
    summary: 'Estimate time complexity with instant feedback.',
    conceptId: 'complexity',
    difficulty: 'Moderate',
  },
];

export const AUTH_PROVIDER_GUIDE = {
  recommendedProvider: 'Supabase Auth',
  reason: 'Supabase covers managed auth, Postgres, storage, and local/staging separation for the MVP.',
  env: [
    'VITE_SUPABASE_URL',
    'VITE_SUPABASE_ANON_KEY',
    'SUPABASE_SERVICE_ROLE_KEY',
    'DATABASE_URL',
    'SANDBOX_API_KEY',
    'SANDBOX_PROVIDER',
    'RESEND_API_KEY',
    'POSTHOG_KEY',
    'SENTRY_DSN',
    'ANTHROPIC_API_KEY',
    'AI_TUTOR_MODEL',
  ],
};

export const GLOSSARY_DICTIONARY = {
  for: { term: 'for loop', def: 'A control flow loop that repeats code a known number of times using an initializer, condition, and update step.', example: 'for (let i = 0; i < 5; i++)' },
  while: { term: 'while loop', def: 'A loop that continues executing as long as a specified boolean condition evaluates to true.', example: 'while (count < 10)' },
  range: { term: 'range()', def: 'A Python sequence builder that generates numbers starting from start up to (but excluding) stop.', example: 'range(1, 11) -> 1, 2, ..., 10' },
  array: { term: 'Array / List', def: 'An ordered collection of items stored at contiguous memory indexes starting at position 0.', example: 'const arr = [10, 20, 30]' },
  index: { term: 'Index', def: 'A zero-based numeric position marker pointing to a specific element inside an array.', example: 'arr[0] is the 1st element' },
  push: { term: 'push()', def: 'Appends a new element onto the top of a Stack or end of an Array.', example: 'stack.push(42)' },
  pop: { term: 'pop()', def: 'Removes and returns the top/most recent element from a Stack or end of an Array.', example: 'const top = stack.pop()' },
  enqueue: { term: 'enqueue()', def: 'Inserts an item at the back/tail of a Queue.', example: 'queue.enqueue(customer)' },
  dequeue: { term: 'dequeue()', def: 'Removes and returns the item at the front/head of a Queue (First-In, First-Out).', example: 'const first = queue.dequeue()' },
  recursion: { term: 'Recursion', def: 'A function calling itself with a smaller input until it hits a stopping rule called the Base Case.', example: 'fact(n) = n * fact(n - 1)' },
  'base case': { term: 'Base Case', def: 'The termination condition in a recursive function that returns a value without making further self calls.', example: 'if (n === 1) return 1;' },
  matrix: { term: '2D Array / Matrix', def: 'A grid of values accessed by row index and column index.', example: 'grid[row][col]' },
};

export const LANGUAGE_GOTCHAS = [
  {
    language: 'Python',
    title: 'Exclusive Range Stop Rule',
    detail: 'range(1, 10) stops at 9, not 10. The upper boundary is exclusive in Python.',
    code: 'for i in range(1, 10): # i goes 1..9',
  },
  {
    language: 'Python',
    title: 'Mutable Default Arguments',
    detail: 'Default parameter values like def add(item, box=[]) persist state across calls.',
    code: 'def append_to(element, target=[]): ...',
  },
  {
    language: 'JavaScript',
    title: 'Var Hoisting vs Let Scoping',
    detail: 'var declarations are hoisted to the top of the function scope, whereas let is block-scoped.',
    code: 'for (var i = 0; i < 3; i++) { setTimeout(() => console.log(i), 100); } // prints 3, 3, 3',
  },
  {
    language: 'JavaScript',
    title: 'Loose vs Strict Equality',
    detail: '0 == "0" evaluates to true due to type coercion. Always prefer === in modern JS.',
    code: '0 == "0" // true, but 0 === "0" // false',
  },
  {
    language: 'C',
    title: 'Pointer Arithmetic & Bounds',
    detail: 'Arrays do not store their length in C. Accessing arr[i] past allocated size leads to undefined behavior.',
    code: 'int arr[5]; int x = arr[10]; // Undefined behavior / memory leak',
  },
  {
    language: 'C++',
    title: 'Pass by Reference vs Pass by Value',
    detail: 'Passing large containers by value copies all elements. Use const std::vector<int>& to avoid overhead.',
    code: 'void process(const std::vector<int>& vec)',
  },
];

export const SAME_ALGORITHM_COMPARISON = [
  {
    id: 'counter-loop',
    title: 'Count 1 to 5',
    python: `for i in range(1, 6):\n    print(i)`,
    javascript: `for (let i = 1; i <= 5; i++) {\n  console.log(i);\n}`,
    c: `#include <stdio.h>\nint main() {\n    for (int i = 1; i <= 5; i++) {\n        printf("%d\\n", i);\n    }\n    return 0;\n}`,
    cpp: `#include <iostream>\nint main() {\n    for (int i = 1; i <= 5; ++i) {\n        std::cout << i << std::endl;\n    }\n    return 0;\n}`,
  },
  {
    id: 'array-filter',
    title: 'Sum Numbers > 5',
    python: `scores = [4, 7, 2, 9]\ntotal = 0\nfor x in scores:\n    if x > 5:\n        total += x\nprint(total)`,
    javascript: `const scores = [4, 7, 2, 9];\nlet total = 0;\nfor (let x of scores) {\n  if (x > 5) total += x;\n}\nconsole.log(total);`,
    c: `int scores[] = {4, 7, 2, 9};\nint total = 0;\nfor (int i = 0; i < 4; i++) {\n    if (scores[i] > 5) total += scores[i];\n}\nprintf("%d\\n", total);`,
    cpp: `std::vector<int> scores = {4, 7, 2, 9};\nint total = 0;\nfor (int x : scores) {\n    if (x > 5) total += x;\n}\nstd::cout << total << std::endl;`,
  },
];

export const CONCEPT_DEPENDENCIES = [
  { id: 'loops-for', name: 'For Loop', dependsOn: [] },
  { id: 'loops-while', name: 'While Loop', dependsOn: ['loops-for'] },
  { id: 'arrays-1d', name: '1D Arrays', dependsOn: ['loops-for'] },
  { id: 'loops-nested', name: 'Nested Loops', dependsOn: ['loops-for', 'loops-while'] },
  { id: 'arrays-2d', name: '2D Arrays / Matrices', dependsOn: ['arrays-1d', 'loops-nested'] },
  { id: 'stack', name: 'Stack (LIFO)', dependsOn: ['arrays-1d'] },
  { id: 'queue', name: 'Queue (FIFO)', dependsOn: ['arrays-1d'] },
  { id: 'linked-list', name: 'Linked List', dependsOn: ['arrays-1d'] },
  { id: 'recursion', name: 'Recursion', dependsOn: ['loops-while'] },
  { id: 'trees', name: 'Trees', dependsOn: ['linked-list', 'recursion'] },
  { id: 'graphs', name: 'Graphs', dependsOn: ['trees', 'queue'] },
  { id: 'sorting', name: 'Sorting Algorithms', dependsOn: ['arrays-1d', 'loops-nested'] },
  { id: 'searching-linear', name: 'Linear Search', dependsOn: ['arrays-1d', 'loops-for'] },
];

export const BILINGUAL_STRINGS = {
  en: {
    hubTitle: 'Learning Hub',
    visualizerTitle: 'Execution Visualizer',
    assessmentTitle: 'Skill Assessment',
    gamesTitle: 'Learning Games',
    confidenceCheck: 'How confident are you in your prediction?',
    sure: 'Sure (100%)',
    unsure: 'Unsure (50%)',
    eli5Mode: 'Simple (ELI5)',
    formalMode: 'Technical (CS Terms)',
    explainError: 'Explain Error',
    worksheet: 'Download Printable Worksheet',
    whatIf: 'What-If Sandbox',
    compareTrace: 'Compare Traces',
    conceptMap: 'Concept Map',
    gotchas: 'Language Gotchas',
    narration: 'Audio Narration',
  },
  es: {
    hubTitle: 'Centro de Aprendizaje',
    visualizerTitle: 'Visualizador de Ejecución',
    assessmentTitle: 'Evaluación de Habilidades',
    gamesTitle: 'Juegos de Aprendizaje',
    confidenceCheck: '¿Qué tan seguro estás de tu predicción?',
    sure: 'Seguro (100%)',
    unsure: 'Inseguro (50%)',
    eli5Mode: 'Explicación Sencilla',
    formalMode: 'Términos Técnicos CS',
    explainError: 'Explicar Error',
    worksheet: 'Descargar Hoja de Trabajo',
    whatIf: 'Modo ¿Qué Pasaría Si?',
    compareTrace: 'Comparar Trazas',
    conceptMap: 'Mapa de Conceptos',
    gotchas: 'Casos Especiales',
    narration: 'Narración de Audio',
  },
  hi: {
    hubTitle: 'लर्निंग हब',
    visualizerTitle: 'एग्जीक्यूशन विज़ुअलाइज़र',
    assessmentTitle: 'कौशल मूल्यांकन',
    gamesTitle: 'लर्निंग गेम्स',
    confidenceCheck: 'क्या आप अपने अनुमान के प्रति आश्वस्त हैं?',
    sure: 'पक्का (100%)',
    unsure: 'अनिश्चित (50%)',
    eli5Mode: 'सरल व्याख्या',
    formalMode: 'तकनीकी शब्द (CS)',
    explainError: 'त्रुटि समझाएं',
    worksheet: 'वर्कशीट डाउनलोड करें',
    whatIf: 'व्हाट-इफ सैंडबॉक्स',
    compareTrace: 'ट्रेस तुलना',
    conceptMap: 'कांसेप्ट मैप',
    gotchas: 'भाषा की बारीकियाँ',
    narration: 'ऑडियो विवरण',
  },
};

export const MISCONCEPTION_PATTERNS = [
  {
    id: 'off-by-one',
    title: 'Possible Off-by-One Boundary Error',
    description: 'Check whether your loop condition i <= length should be i < length for 0-indexed arrays.',
  },
  {
    id: 'range-stop',
    title: 'Python Range Exclusive Stop',
    description: 'Remember range(a, b) generates numbers up to b - 1.',
  },
  {
    id: 'zero-index',
    title: 'Zero-Based Indexing Reminder',
    description: 'Array element 1 is stored at index 0.',
  },
];
